let events = [
  // {id:, title:, startDate:, endDate:, img:null, description:},
  {id:9, title:'Matura Beach Cleanup', startDate:'2020-03-01', endDate:null, img:'images/events/Matura2020.jpg', description:'Approximately 75 scouts, parents and family members attended this year cleanup of Matura Beach. The scouts removed over 20 bags of debris, plastics and other materials. After the clean up, the scouts participated in the sand turtle competition and placed 3rd. We look forward to being a part of this event next year.'},
  {id:8, title:'Carnival Camp', startDate:'2020-02-21', endDate:'2020-02-23', img:null, description:'Camp began on the 21st of February and ended on the 23rd. It was attended by 25 scouts and 5 past scouts. On the 21st all scouts arrived at the boathouse for 4:00pm and set up for the camp. During the camp, scouts partook in activities including learning about scout history, learning first aid, performing carnival skits, rowing, etc. This camp was used to aid new scouts in fulfilling the requirements of being invested such as knot tying and scout laws. On the 23rd the scouts packed away all equipment and were dismissed from the boathouse.'},
  {id:7, title:'Christmas Vacation Camp', startDate:'2019-12-14', endDate:'2019-12-17', img:null, description:'Camp was from the 14th to 17th of December and was attended to by 30 scouts and 10 past scouts. On the morning of the    14th all camping equipment, as well as luggage, was sent to Pt. Gourde and a crew rowed to the campsite. At camp the scouts partook in activities such as playing capture the flag, wrestling, bonfire songs and skits, learning scout skills, etc. Some of the skills taught to the newer scouts were oarsmanship, knot tying, and first aid. On the 16th we transported the equipment back to boathouse and ended camp there the following day.'},
  {id:6, title:'Rosary Procession to close the 40 Day Rosary for Life', startDate:'2019-09-08', endDate:null, img:'images/events/Rosary2019.png', description:'Scouts attended the Marian Procession to close the 40 Day Rosary for Life at the Queens Park Savannah. The scouts are pictured above with Archbishop Jason Gordon.'},
  {id:5, title:'First Aid Training', startDate:'2019-08-18', endDate:null, img:null, description:'Eight scouts attended a first aid course on Sunday August 18 at the Boathouse. The course covered a wide range of first aid procedures.'},
  {id:4, title:'July/August Vacation Camp', startDate:'2019-07-05', endDate:'2019-07-09', img:'images/events/Tobago2019_2.jpg', description:'Twenty scouts attended July/August Vacation Camp in Tobago from July 5th - 9th.'},
  {id:3, title:'World Youth Affairs Seminar 2019', startDate:'2019-06-01', endDate:null, img:'images/events/WorldAffairsSeminar2019.png', description:'Gabriel Stewart was chosen to represent Trinidad at the World Youth Seminar in Wisconsin in June. This follows a request from Rotary Club for 1st TSS to have scouts in the qualifying age group to apply. In 2017 Dexter Blackman was chosen and in 2018 Christian Harper, both members of the troop.'},
  {id:2, title:'Investiture', startDate:'2019-04-28', endDate:null, img:'images/events/Investiture2019.png', description:'Sa’id Achille, Taariq Alexander, Terrell Anthony, Ethan Bachew, Christian Bullen, Kyle Chase, Aidan Douglas-Mohammed, Jovani Haynes, Daniel Hope, Jonah La Croix, Jaedon Moore, Kamosi Romero, and Jaheim Williams were invested into the troop.'},
  {id:1, title:'Easter Camp', startDate:'2019-04-06', endDate:'2019-04-09', img:null, description:'Easter camp was held from Saturday April 6 to Tuesday April 9, 2019.' },
]
